"""Model price map maintenance — litellm-backed refresh (manual + periodic).

The observability cost estimator reads `model_prices` from settings
(config/launchpad.yaml). This module refreshes that map from litellm's
public price file (per-token USD costs → per-1M entries):

- models seen in the account's telemetry get exact full-id entries
  (regional Bedrock prices differ, e.g. us.* carries a premium over global.*),
- the operator's short fallback keys ("sonnet-4-6") get their numbers
  refreshed from the most canonical matching source entry,
- unmatched keys are preserved untouched.

Only the local config file is written — no AWS resource is mutated. The
periodic refresher is a daemon thread started with the real server
(create_app(resume_jobs=True)), skipped in tests.
"""

import json
import logging
import threading
import time
import urllib.request
from datetime import UTC, datetime
from typing import Any

import boto3
import yaml

from app.core import config as config_module
from app.core.config import get_settings
from app.core.errors import AppError

MAX_SOURCE_BYTES = 30 * 1024 * 1024
PREFERRED_PROVIDERS = ("bedrock_converse", "bedrock", "anthropic")
CONFIG_HEADER = (
    "# Generated by scripts/bootstrap.py; model_prices maintained by the price\n"
    "# refresher (app/services/model_prices.py) — do not commit (gitignored).\n"
)

_REFRESH_LOCK = threading.Lock()
_logger = logging.getLogger("launchpad.prices")


def _fetch_source(url: str) -> dict[str, Any]:
    request = urllib.request.Request(url, headers={"User-Agent": "agentcore-launchpad"})
    with urllib.request.urlopen(request, timeout=30) as response:
        raw = response.read(MAX_SOURCE_BYTES + 1)
    if len(raw) > MAX_SOURCE_BYTES:
        raise AppError("prices.source_too_large", "price source exceeds size cap",
                       status_code=502)
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise AppError("prices.bad_source", "price source is not a JSON object",
                       status_code=502)
    return data


def _entry_from_litellm(spec: dict[str, Any]) -> dict[str, float] | None:
    """litellm per-token USD costs → our per-1M entry; None when unpriced."""
    try:
        cost_in = float(spec["input_cost_per_token"])
        cost_out = float(spec["output_cost_per_token"])
    except (KeyError, TypeError, ValueError):
        return None
    if cost_in < 0 or cost_out < 0:
        return None
    entry = {"input": round(cost_in * 1e6, 4), "output": round(cost_out * 1e6, 4)}
    for src, dst in (
        ("cache_read_input_token_cost", "cache_read"),
        ("cache_creation_input_token_cost", "cache_write"),
    ):
        value = spec.get(src)
        if isinstance(value, (int, float)) and value >= 0:
            entry[dst] = round(float(value) * 1e6, 4)
    return entry


def _chat_catalog(source: dict[str, Any]) -> list[tuple[str, dict[str, float], str]]:
    catalog = []
    for name, spec in source.items():
        if not isinstance(spec, dict) or spec.get("mode") != "chat":
            continue
        entry = _entry_from_litellm(spec)
        if entry is not None:
            catalog.append((name, entry, str(spec.get("litellm_provider", ""))))
    return catalog


def refresh_map(
    current: dict[str, Any], seen_models: list[str], source: dict[str, Any]
) -> tuple[dict[str, Any], list[str], list[str]]:
    """Pure merge step: returns (new_prices, updated_keys, added_keys)."""
    catalog = _chat_catalog(source)
    by_lower = {name.lower(): (name, entry) for name, entry, _ in catalog}
    prices: dict[str, Any] = {k: dict(v) if isinstance(v, dict) else v
                              for k, v in current.items()}
    updated: list[str] = []
    added: list[str] = []

    # 1. exact full-id entries for models actually seen in telemetry
    for model in seen_models:
        hit = by_lower.get(model.lower())
        if hit is None:
            continue
        entry = hit[1]
        if prices.get(model) == entry:
            continue
        (updated if model in prices else added).append(model)
        prices[model] = dict(entry)

    # 2. refresh the operator's short substring keys from the most canonical
    #    matching source entry (preferred provider, then shortest name)
    def rank(item: tuple[str, dict[str, float], str]) -> tuple[int, int, str]:
        name, _, provider = item
        provider_rank = (
            PREFERRED_PROVIDERS.index(provider)
            if provider in PREFERRED_PROVIDERS
            else len(PREFERRED_PROVIDERS)
        )
        return (provider_rank, len(name), name)

    for key in current:
        if key in updated or key in added:
            continue
        candidates = [item for item in catalog if key.lower() in item[0].lower()]
        if not candidates:
            continue
        _, entry, _ = min(candidates, key=rank)
        if prices.get(key) != entry:
            prices[key] = dict(entry)
            updated.append(key)

    return prices, updated, added


def _seen_models(cw: Any = None) -> list[str]:
    """Model ids with recent token-usage metrics; empty on any AWS failure."""
    try:
        cw = cw or boto3.client("cloudwatch", region_name=get_settings().region)
        models: set[str] = set()
        paginator = cw.get_paginator("list_metrics")
        for page in paginator.paginate(
            Namespace="bedrock-agentcore", MetricName="gen_ai.client.token.usage"
        ):
            for metric in page["Metrics"]:
                for dim in metric["Dimensions"]:
                    if dim["Name"] == "gen_ai.request.model":
                        models.add(dim["Value"])
        return sorted(models)
    except Exception:
        return []


def _persist(prices: dict[str, Any], meta: dict[str, Any]) -> None:
    path = config_module.CONFIG_FILE
    data = config_module.load_yaml_config(path)
    data["model_prices"] = prices
    data["model_prices_meta"] = meta
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        CONFIG_HEADER + yaml.safe_dump(data, allow_unicode=True, sort_keys=True),
        encoding="utf-8",
    )


def refresh_model_prices(
    source_url: str | None = None, cw: Any = None, fetch: Any = None
) -> dict[str, Any]:
    """Fetch the price source, merge, persist, and apply immediately."""
    with _REFRESH_LOCK:
        settings = get_settings()
        url = source_url or settings.model_prices_source_url
        if not url.startswith("https://"):
            raise AppError("prices.bad_source", "price source url must be https",
                           status_code=400)
        try:
            source = (fetch or _fetch_source)(url)
        except AppError:
            raise
        except Exception as exc:
            raise AppError(
                "prices.fetch_failed", f"{type(exc).__name__}: {exc}"[:200],
                status_code=502,
            ) from exc
        seen = _seen_models(cw)
        prices, updated, added = refresh_map(settings.model_prices, seen, source)
        meta = {
            "updated_at": datetime.now(UTC).isoformat(timespec="seconds"),
            "source": url,
            "source_models": len(source),
            "updated": sorted(updated),
            "added": sorted(added),
        }
        _persist(prices, meta)
        get_settings.cache_clear()  # new prices take effect without a restart
        return {"prices": prices, "meta": meta, "seen_models": seen}


def _due(hours: int) -> bool:
    meta = get_settings().model_prices_meta
    stamp = meta.get("updated_at") if isinstance(meta, dict) else None
    if not stamp:
        return True
    try:
        last = datetime.fromisoformat(str(stamp))
    except ValueError:
        return True
    return (datetime.now(UTC) - last).total_seconds() >= hours * 3600


def start_auto_refresh() -> threading.Thread | None:
    """Daemon thread: refresh when the map is older than the configured
    interval. Restart-safe — the last-updated stamp lives in the config."""
    hours = get_settings().model_prices_refresh_hours
    if hours <= 0:
        return None

    def loop() -> None:
        time.sleep(90)  # let the server settle before the first check
        while True:
            try:
                if _due(hours):
                    result = refresh_model_prices()
                    _logger.info(
                        "model_prices refreshed: %d updated, %d added",
                        len(result["meta"]["updated"]), len(result["meta"]["added"]),
                    )
            except Exception as exc:
                _logger.warning("model_prices auto-refresh failed: %s", exc)
            time.sleep(3600)

    thread = threading.Thread(target=loop, daemon=True, name="model-prices-refresh")
    thread.start()
    return thread
